import Link from '@/node_modules/next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="flex justify-center p-14">
        <ul className="flex text-lg gap-4">
        <li>
            <Link href="/">Home</Link>

          </li>
          <li>
            <Link href="/">Featured Products</Link>

          </li>
          <li>
            <Link href="/about">New Arrivals</Link>
          </li>
          <li>
            <Link href="/showcase">Special Offers</Link>
          </li>
          <li>
            <Link href="/showcase">Community and Engagement</Link>
          </li>
          <li>
            <Link href="/showcase">User resources</Link>
          </li>
          <li>
            <Link href="/showcase">Account</Link>
          </li>
          <li>
            <Link href="/showcase">About us</Link>
          </li>
          <li>
            <Link href="/showcase">Contact us</Link>
          </li>
        </ul>
      
      </nav> 
        
        {children}
      </body>
    </html>
  )
}
